# Generated by Django 6.0 on 2026-03-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='task_asset/default.png', upload_to='profile_image'),
        ),
    ]
